spring:
  security:
    user:
      name: user
      password: user
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb+srv://koderkt:Ren0707@cluster0.b2bllgk.mongodb.net/?retryWrites=true&w=majority
      database: stray-animals

cloud:
  aws:
    credentials:
      access-key: AKIAS7KYZQTIU5GG6GHJ
      secret-key: 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
    region:
      static: ap-south-1

application:
  bucket:
    name: stray-animals


